# Generated by Django 6.0.2 on 2026-03-02 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(help_text='Minimum 255 characters', validators=[django.core.validators.MinLengthValidator(255)]),
        ),
    ]
